export const KNOWN_SKILLS = [
  "instructional design",
  "storyboarding",
  "articulate 360",
  "rise",
  "captivate",
  "prompt engineering",
  "prompt design",
  "prompt writing",
  "generative ai",
  "ai content creation",
  "image generation",
  "video generation",
  "animation",
  "motion graphics",
  "video editing",
  "after effects",
  "premiere pro",
  "photoshop",
  "illustrator",
  "runway",
  "kling",
  "veo",
  "seedream",
  "eleven labs",
  "google flow",
  "learning strategy",
  "learning design",
  "leadership development",
  "facilitation",
  "analytics",
  "lms",
  "learning management system",
  "reporting",
  "stakeholder management",
  "stakeholder communication",
  "onboarding",
  "curriculum design",
  "microlearning",
  "canva",
  "figma",
  "visual design",
  "program management",
  "project management",
  "course production",
  "needs analysis",
  "xapi",
  "scorm",
  "evaluation",
  "workshop design",
  "training delivery",
  "content writing",
  "elearning",
  "adult learning",
  "performance consulting",
];

export const KNOWN_ROLE_PATTERNS = [
  "instructional designer",
  "senior instructional designer",
  "learning experience designer",
  "learning designer",
  "elearning developer",
  "e-learning developer",
  "ld specialist",
  "l&d specialist",
  "ld manager",
  "l&d manager",
  "program manager",
  "facilitator",
  "facilitation consultant",
  "curriculum designer",
  "training specialist",
  "training manager",
  "learning consultant",
  "prompt engineer",
  "ai content creator",
  "video generation specialist",
  "motion designer",
  "animator",
  "video editor",
  "operations specialist",
  "learning operations specialist",
];
