export const KNOWN_SKILLS = [
  "instructional design",
  "storyboarding",
  "articulate 360",
  "rise",
  "captivate",
  "learning strategy",
  "learning design",
  "leadership development",
  "facilitation",
  "analytics",
  "lms",
  "learning management system",
  "reporting",
  "stakeholder management",
  "stakeholder communication",
  "onboarding",
  "curriculum design",
  "microlearning",
  "canva",
  "figma",
  "program management",
  "project management",
  "course production",
  "needs analysis",
  "xapi",
  "scorm",
  "evaluation",
  "workshop design",
  "training delivery",
  "content writing",
  "elearning",
  "adult learning",
  "performance consulting",
];

export const KNOWN_ROLE_PATTERNS = [
  "instructional designer",
  "senior instructional designer",
  "learning experience designer",
  "learning designer",
  "ld specialist",
  "l&d specialist",
  "ld manager",
  "l&d manager",
  "program manager",
  "facilitator",
  "facilitation consultant",
  "curriculum designer",
  "training specialist",
  "training manager",
  "learning consultant",
  "operations specialist",
  "learning operations specialist",
];
